# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "imagick"

  loaders:
    flysystem_loader:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
  # default loader to use for all filter sets
  data_loader: flysystem_loader
  resolvers:
    flysystem_resolver:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
        cache_prefix: media/cache
        root_url: '%uploads_base_url%'
  # default cache resolver for saving thumbnails
  cache: flysystem_resolver
  filter_sets:
    #
    #        # an example thumbnail transformation definition
    #        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
    squared_thumbnail_small:
      filters:
        thumbnail:
          size:          [200, 200]
          mode:          outbound
          allow_upscale: true
    squared_thumbnail_medium:
      filters:
        thumbnail:
          size:          [500, 500]
          mode:          outbound
          allow_upscale: true