nelmio_api_doc:
    documentation:
        info:
            title: Tecspec CRM
            description: Tecspec CRM Api Docs
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/private(?!/doc$) # Accepts routes under /api except /api/doc
