nelmio_api_doc:
    documentation:
        schemes: [https]
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
          - Bearer: []
    areas: # to filter documented areas
        default:
            path_patterns: [ ^/test ]
            documentation:
                info:
                    title: Tecspec CRM
                    description: Tecspec CRM Api Docs
                    version: 1.0.0
        v1:
            path_patterns: [ ^/api/v1 ]
            documentation:
              info:
                title: Tecspec CRM v1
                description: Tecspec CRM v1 Api Docs
                version: 1.0.0
            #with_annotation: false
        v2:
          path_patterns: [ ^/api/v2 ]
          documentation:
            info:
              title: Tecspec CRM v2
              description: Tecspec CRM v2 Api Docs
              version: 2.0.0
