security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # User Providers (Should have one per firewall)
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_jwt_user_provider:
             id: app.jwt_user_provider
        app_api_key_user_provider:
             id: app.api_key_user_provider

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        private_api:
            guard:
                authenticators:
                      - app.jwt_guard_authenticator
            request_matcher: app.security.private_api_request_matcher
            provider: app_jwt_user_provider
            stateless: true
        marketing_api:
            guard:
                authenticators:
                      - app.api_key_guard_authenticator
            request_matcher: app.security.marketing_request_matcher
            provider: app_api_key_user_provider
            stateless: true


            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/v1/private, roles: ROLE_ADMIN_USER }
        - { path: ^/api/v1/marketing, roles: [ROLE_API_KEY_USER] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/password-reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/.*$, roles: ROLE_ADMIN_USER }
