app.swagger_ui_v1:
  path: /api/doc/v1/private
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: private }
app.swagger_ui_v2:
  path: /api/doc/v2/private
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: private_v2  }
