#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
  path: /logout
login:
  path: /login
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }